# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(857, 1030)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(440, 950, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(50, 150, 631, 71))
        self.groupBox.setObjectName("groupBox")
        self.radioButton_1 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_1.setGeometry(QtCore.QRect(30, 20, 51, 19))
        self.radioButton_1.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_2.setGeometry(QtCore.QRect(90, 20, 51, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_3.setGeometry(QtCore.QRect(150, 20, 51, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_4.setGeometry(QtCore.QRect(210, 20, 51, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_5.setGeometry(QtCore.QRect(280, 20, 51, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_6.setGeometry(QtCore.QRect(340, 20, 51, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_7.setGeometry(QtCore.QRect(390, 20, 51, 19))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_8.setGeometry(QtCore.QRect(440, 20, 51, 19))
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_9 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_9.setGeometry(QtCore.QRect(500, 20, 51, 19))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_10.setGeometry(QtCore.QRect(560, 20, 51, 19))
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_11 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_11.setGeometry(QtCore.QRect(30, 50, 51, 19))
        self.radioButton_11.setObjectName("radioButton_11")
        self.radioButton_12 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_12.setGeometry(QtCore.QRect(90, 50, 51, 19))
        self.radioButton_12.setObjectName("radioButton_12")
        self.radioButton_13 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_13.setGeometry(QtCore.QRect(150, 50, 51, 19))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_14.setGeometry(QtCore.QRect(210, 50, 51, 19))
        self.radioButton_14.setObjectName("radioButton_14")
        self.radioButton_15 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_15.setGeometry(QtCore.QRect(280, 50, 51, 19))
        self.radioButton_15.setObjectName("radioButton_15")
        self.radioButton_16 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_16.setGeometry(QtCore.QRect(340, 50, 51, 19))
        self.radioButton_16.setObjectName("radioButton_16")
        self.radioButton_17 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_17.setGeometry(QtCore.QRect(390, 50, 51, 19))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_18.setGeometry(QtCore.QRect(440, 50, 51, 19))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_19.setGeometry(QtCore.QRect(500, 50, 51, 19))
        self.radioButton_19.setObjectName("radioButton_19")
        self.radioButton_20 = QtWidgets.QRadioButton(self.groupBox)
        self.radioButton_20.setGeometry(QtCore.QRect(560, 50, 51, 19))
        self.radioButton_20.setObjectName("radioButton_20")
        self.bg = QButtonGroup(self)
        self.bg.addButton(self.radioButton_1, 0)
        self.bg.addButton(self.radioButton_2, 1)
        self.bg.addButton(self.radioButton_3, 2)
        self.bg.addButton(self.radioButton_4, 3)
        self.bg.addButton(self.radioButton_5, 4)
        self.bg.addButton(self.radioButton_6, 5)
        self.bg.addButton(self.radioButton_7, 6)
        self.bg.addButton(self.radioButton_8, 7)
        self.bg.addButton(self.radioButton_9, 8)
        self.bg.addButton(self.radioButton_10, 9)
        self.bg.addButton(self.radioButton_11, 10)
        self.bg.addButton(self.radioButton_12, 11)
        self.bg.addButton(self.radioButton_13, 12)
        self.bg.addButton(self.radioButton_14, 13)
        self.bg.addButton(self.radioButton_15, 14)
        self.bg.addButton(self.radioButton_16, 15)
        self.bg.addButton(self.radioButton_17, 16)
        self.bg.addButton(self.radioButton_18, 17)
        self.bg.addButton(self.radioButton_19, 18)
        self.bg.addButton(self.radioButton_20, 19)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(690, 230, 93, 41))
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setGeometry(QtCore.QRect(50, 20, 551, 121))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(130, 30, 16, 61))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(28)
        self.label_3.setFont(font)
        self.label_3.setLineWidth(1)
        self.label_3.setMidLineWidth(1)
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit.setGeometry(QtCore.QRect(145, 30, 31, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 40, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(145, 60, 31, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(360, 30, 31, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setLineWidth(1)
        self.label_2.setMidLineWidth(1)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(40, 60, 72, 15))
        self.label.setText("")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(690, 160, 93, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(660, 30, 72, 15))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(680, 50, 181, 16))
        self.label_5.setObjectName("label_5")
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 230, 631, 41))
        self.groupBox_3.setObjectName("groupBox_3")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox.setGeometry(QtCore.QRect(60, 20, 111, 19))
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_3)
        self.checkBox_2.setGeometry(QtCore.QRect(210, 20, 111, 19))
        self.checkBox_2.setObjectName("checkBox_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setGeometry(QtCore.QRect(50, 280, 731, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.textBrowser = QtWidgets.QTextBrowser(self.groupBox_4)
        self.textBrowser.setGeometry(QtCore.QRect(30, 20, 641, 101))
        self.textBrowser.setObjectName("textBrowser")
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setGeometry(QtCore.QRect(50, 420, 731, 491))
        self.groupBox_5.setObjectName("groupBox_5")
        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.pushButton_2.clicked.connect(self.lineEdit_3.clear)
        self.pushButton_2.clicked.connect(self.lineEdit_2.clear)
        self.pushButton_2.clicked.connect(self.lineEdit.clear)
        self.pushButton.clicked.connect(Dialog.operation)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "精度选择"))
        self.radioButton_1.setText(_translate("Dialog", " 0"))
        self.radioButton_2.setText(_translate("Dialog", " 1"))
        self.radioButton_3.setText(_translate("Dialog", " 2"))
        self.radioButton_4.setText(_translate("Dialog", " 3"))
        self.radioButton_5.setText(_translate("Dialog", " 4"))
        self.radioButton_6.setText(_translate("Dialog", " 5"))
        self.radioButton_7.setText(_translate("Dialog", " 6"))
        self.radioButton_8.setText(_translate("Dialog", " 7"))
        self.radioButton_9.setText(_translate("Dialog", " 8"))
        self.radioButton_10.setText(_translate("Dialog", " 9"))
        self.radioButton_11.setText(_translate("Dialog", " 10"))
        self.radioButton_12.setText(_translate("Dialog", "11"))
        self.radioButton_13.setText(_translate("Dialog", "12"))
        self.radioButton_14.setText(_translate("Dialog", "13"))
        self.radioButton_15.setText(_translate("Dialog", "14"))
        self.radioButton_16.setText(_translate("Dialog", "15"))
        self.radioButton_17.setText(_translate("Dialog", "16"))
        self.radioButton_18.setText(_translate("Dialog", "17"))
        self.radioButton_19.setText(_translate("Dialog", "18"))
        self.radioButton_20.setText(_translate("Dialog", "19"))
        self.pushButton.setText(_translate("Dialog", "运算"))
        self.groupBox_2.setTitle(_translate("Dialog", "积分函数："))
        self.label_3.setText(_translate("Dialog", "∫"))
        self.label_2.setText(_translate("Dialog", "dx"))
        self.pushButton_2.setText(_translate("Dialog", "清空"))
        self.label_4.setText(_translate("Dialog", "使用说明："))
        self.label_5.setText(_translate("Dialog", "1.次方请使用“**”"))
        self.groupBox_3.setTitle(_translate("Dialog", "算法选择"))
        self.checkBox.setText(_translate("Dialog", "高斯-勒让德"))
        self.checkBox_2.setText(_translate("Dialog", "scipy库"))
        self.groupBox_4.setTitle(_translate("Dialog", "结果输出"))
        self.groupBox_5.setTitle(_translate("Dialog", "函数图像："))
    def operation(self):
        pass # 在子类中重写
